import { create } from "zustand";

const ENCRYPTED_DATA = [
  "LhoRBgBOHRsKCgYDQ1ICD6LMBRJXAhsKHwESVBtOCB0cBACm6lIdAUcZDwQSHAYdCR8SVBZOOwOr1hhCGxMFCwkETw==",
  "PgIcHgROHxUEBhdCHAYIBKP1QQAeq+tEGRwfGggLBQcSAFIYTxkIq9sUpfZXFRMDGBQdsOROAQEcofdM",
  "Lg8aBwgLBQcSHFIWHRcHBwkXQQMFFQsGBhy2yBir7VQrDLb7TxYGTgoZEgcFFR0XHgISWg==",
  "OhoQDhQETxAdCLb7T5Dp/UcHpPEWqukKAxBTDhMBDR2t5xen9FICHAgbQR0WHwAeqcYXWg==",
  "PgIcHgBODB0NFwIOBgUGq/y05lMDAFIwHRoZFUEADh4fDLb7BAETD0cdFAkODAgKC1UAARELHRkHBlw=",
  "IAAHBhsLBQcSHFI2FlIZAQMKCLfuBAcOD1UwHUEUDlQMHxsRBhcDHR0JQQQOHBuh6BAYWg==",
  "JwAJDQoPQ1QDEbHRHbbsThMHDgENFgEeRlUZERIaTwEGDBkDAxwQA0cfBREeDBsBB1UnAw4ECh5IAQcRFQtH",
  "MFUYFaTSCw0FRRMJAAANCwpQAwYTGhgBGQ9TGAQeHA6s4FIVCgAaBKPpQQAeChAND1s=",
  "LQcSGggLTxoJRRULGxMbFAJQFRxXHR0eBxoEFUEMCg5IFrfgrMEeQkcbFbDEHbbhSgK29gCr9BoBAFINHxMHARAFCxYEFVw=",
  "PhpTFhir7VQbCh4LCxwQThMCBB0eARVISgESH0EaHQ4RCBMITg==",
  "PgIcHgBOGxELDRwLBBNJHRMRCxZXHBug81UQGxMPFVQKBAAGFRsMBEcAExYUFggdABsSWg==",
  "IRS2yAULTwQHERkMBrbwDQ4VQRcNBgENCx9TAA5OAxEDBhgDQ1ICGqTDExJXFRMUGBoQEQ8aGh4NRRgXGwAGQA==",
  "IBAAAASr9FQHRRgHCxcHTgMKCBay61IGBhy2yAQETxAHRQEVABAGCgkVC1MeAgIWBQIaDgANBR1G",
  "LQcSGggLTxoJRRULGxMbFAJQExwNGBsOC1Uet9IUCFSK5eFCCwgAq/xQBRKy7Reh8VUeAUGr9AMBAAYMFlIeFwQZEhhZ",
  "OhQeHaX3GxUCSVKn0xdJAAYHBAdXARMOHRy37QodBlQFDAEWHQgGGQ4VQQkWDAgdBBQfHUEBC1QcABUNTwEIAwIXDlMaBhcOGRYSWg==",
  "PgIcHgBOHxUbDxNCBRcaGkcDpPEOHAgFBhsSVBZOBBWt2RYbAlINq90HCLfuBAdK",
  "JBwWVBEcFREbEROn7Res9Ue05gQeDAgdrvJfVAYKFlQKHLfgAFIdHBIUDxxXjfL3SgEcVAILDBwJRQgVFhEAqv4KAgpZ",
  "LrDJAwiq9h9IFgYQGhxJGghQDxIdHxug8x4dHQQEHA4JRRwDCAAGCgZQGxJXOwULALH2VAUXHBcRFR4LAbbwQA==",
  "PbDxFaT1AR0NRQgAGhYGGQa14xay9FIKBQK38UGr9BcBALfeBLbwTgkVFAEYAR0TrvBTA0EdGBsCABhCCLfrARAZBF0=",
  "LRwHFRMPTwELHwtCHx0CARUJQRpXARMDGBQXDgBOGA0cFwUDqvAQDQ9e",
  "Jxq2yAQdFVQKHLblTwhJHQ4VAxoSTxYRBxsKWEGr0xFIHxwDAxMTq+UVpOhXDAgFGVUdFUEDGg4RDrb7QQ==",
  "MFUYFaTSC7DtRQEHHBit60cXCAcWHRNEGQESHgROHB2s/FIADgANFA4VC1MUFbb9r+4QHaXrTzcBABALClw=",
  "PgIcHgROHxsLHwcBBhdJHB4EDAZXCgULBgAGHgROFVQDBLfeC7bsTgoZDwYDq/dErvIEHQIUCrHsSw==",
  "PhpfVAIBTxASDLf5TwUQCgYaBFMEBrb9SgEBAQUAClhICxsHC7frGwAfQQADDhwND1UAHaX3TyAfChim6lIbAR0XEwkSGBmg71s=",
  "JwAJDQoPTwAHRQUNAxwGq/y05l9XDlIwE1UEseMPqu8GDBdCGAseDwsTGwqy7Reh8VUZEQtOBBsEABgMFlICDxARpPESBFw=",
  "IRS2yAUXTwYdBhpCHxMFDQZQFRxXAhOh6BBTDhYXDB2s/AEWGB1JAAYUQR4WGxcWA7H2Wg==",
  "PgIcHgBOCxEcAAAPBhwIDQ0RQRkSHAZEDRoXGgBOHxsMHxsVGlw=",
  "Lg8aBwgPBVQYChkDFROs7AK1+l9Xqs4BSg8SGASr0w1IJhtCARNJOhAfCB5XHR0eHRoZAU8=",
  "LQcSVA8PTxMBERMQFRdJGghQDBIFDgYLBFlTFUE6FlQfoPADqukHBwJQEQENChANDxK29gSr9FSt/gULCgYHF0cfBRAeARcPRA==",
  "OhoQDhQETwANC1IRHx0CrdQaQQMYTxUWCxsaAUGM7+dIER1CFRMaq+UFpM8YARNEBBQUBg4KDlo=",
  "OQESHgQdFVQbDLb7TxMbDQ8ZFRYcGxcJSgK29gAdAREPClIAHQgEBwIeCBJZ",
  "JBwWVAwPTxAaChULTxwIThQbE7DEGwtIShQfEUE6GBsCBFIGHR0OD0caBAADTxQFGRYKGhQEq/ELBFw=",
  "PgIcHgROGgcSHFIRGxMDquJQEhqz9lIHBQcSDkEMDgYMHxsHBVIeHAa13R8eGBdEBBRTEAQaDhgNSw==",
  "LRwHFRMPTwAHRQIQFQsDDwQZBB9bTxkQqcYBEQwbTwQHoOkVBrbwDQ614xay9FIAEBy270EZDgYcCrf5DBsGGR5QAgkWHFw=",
  "IRS2yAUPTwcNFhgDT7buGQ4TGxay61IQBVUQEQYHCrHqDhNCGFILGwMfFh8eTyYTBR8WEw5OHAEDBhcRGlw=",
  "OhoQDhQEQ1QCBBlCARMZB6PpAhoSTwgKAx4SWEEUAAccBAULDhit6wRQDBoSBQEHD1UXGABOAgESHBkLQQ==",
  "PgIcHgBOBAYNBAYbGBwGq/y05lMFAAgPHRwHFUEZHRUSRQhCARMcBaP1QR0YGAsHAlUHEQIGAR0DSw==",
  "IBAAAASr9FQcErHRHRGt60tQAFMeAQEQGAAeEQ8aTwAHRSYVABgMTgkREwmz9hYeAxBTAxgcDg4dSw==",
  "Lg8asfpODQ2t5xen9FIFCxcDGwpXABZEHRYJGxMPBQcSABUNTwEACwUZBF0=",
  "IRS2yAUXTxcSHAEWFlINq90HCLfuBFIQBVUXGxat3BBICxNCOwWq3Q1QERwEG7b9Gls=",
  "PgIcHgBOGA0cFwUDqvAGq/y05lMAT7bjHRwQDgQABgFIFhkDAxtJHhUKGB0eCgEND1UcAw4NClo=",
  "JwAJDQoPTwAHRRim9ggQBUcHEgkSDBqh8QIaFRUPQ1QJRSYbTwcKFB4DG1MEBrb9ShIcVBGr7Q0GCxsHQQ==",
  "OhQeHaX3GxUCSVKn0xdJHAYUDrbsq/VEEFUUBhhOBREbEVIVDrfVAA4VCwANDlIKA7DPVBELHRINDhEIDlw=",
  "PgIcHgROC7HqChwLClIcDR205FMEBrb9ShgSEwgHQQ==",
  "MBoAAAAZBrHqALf5TxYTB6LrQR0WTxUWExMaEUENFbDtFgYJq+tJHRAfCxYdTxcKDwcUHQhA",
  "IRS2yAUXTwAaABwLARVJDBIUFBkSTyYTBR+38UEDGg4RBggMq/dJHgIHDxyy9LbjSgYaEQMHClo=",
  "OQESHgQdFVQbDLb7TxEGHAYKQREWHRYeAxAZVKT1GB0JAR0PFh9JAxIKGBgeCh9K",
  "PgIcHgBOHxUbDxNCBhwaHg4CFBkSTxsKBAwQHE1OARUfAAZCBRes9QsZQRxXGwsJShsaEUEZBhEbH1w=",
  "LQcSGggLTxoJRRULGxMbFAJQFRxXARMOBhADBxsPTx0GEhcRGwsKBAZQFlMjGB0OD1UAFQwBHxsLHwcBBhdH",
  "r+8EHQQaAR0NRQINHRMNFA614xay9FIXBRcaEUEUTxASDAELChgaFB4dCFMAFggTCxsaFQwHQQ==",
  "PgIcHgROAhUaHxcMBhNJAUcXExIZBgdEBBQRHQQcDh6s4FIQChMFAB4TCVMcHAgQC7DxAKLdGFo=",
  "OhoQDhQETwcJEQsRCRMCDQ20+FMNTxYLCAcJEUEZFh8HCxMMChhJHhURAgpZ",
  "JBQEERVOBAar1gYJDlIaCxQaAFMHHQgdCBkasd0PTzcBoetCCx1JDQIcFF0=",
  "LRwHFRMPTwAHRSYVABgITggUEhgYDAgKAxRTluH9TxASDLf5TwUQBQgCGwoEGxOh6BC270EEq/FIDBYHDh4HBwJe",
  "IBAAAASr9FQLCgADFVILAg613RYdTwgKCxkWDggLAR0JRQEVABgMCQhQFB0eBBMIBBAUG0EdGw0EEFw=",
  "PgIcHgBOBBsGEQANAxNJAAYUQRoZHAYWHxgWGhULAlQCAAEWTxEGHAYKQQQeq+sPGQ8SWg==",
  "LrDJAwiq9h8BSVIJG7HaHAJQFgoTABAdHRQADk1OAhUCofdCDB0bDx1QFhqz9hEBAFURFRMZQQ==",
  "LgwAFxgeAx0GBFIWAFIEARQEQR4eq+sAEAxTFwQCChlIBFINHBut6wAeCLfuDBsBB1WR9PJOGLHqBLf5ARsMThcfQR0eAlINDg8aERIUQQ==",
  "PgIcHgBOAgESHBEYARNJHggUE7DEqs5EABAAAEEEChARCxNCGFIaGQgZDFMFABYeCx8GWg==",
  "IRS2yAUXTwAaEBYMFlIPHAYXDBYZG15EAQGwxxMXT7DvEhsBFQus7AK1+l9XCwgNr+5TGggLDBtIChYSGrfyDQ61410=",
  "JwAJDQoPT7HqBBUNCwgAThQEExYEQ1IFSiEKVBar7RWt/hwLClIZAQMRExwADrfmD7DoVBIBDR0NRRYDGBmt90cDERwcABgRRA==",
  "PgIcHgROHxUEBhdCHxMEB6PpFRIdq/dEHRy37QILBVhICxun01IqB0cDCLfuTwUdDhQZEU8=",
  "LQcSGggLTwAHRR8HCwsdDwQaAFMATwARCR0GVIPu/FQMHxum9hkcBKPpTVOy0xdEHhpTBg4MBgcSSw==",
  "PbDxFaT1AR0NRQEWDrfrC6LrQQAeq+tEAxsABAgcDhcCofdCCx4IThQRDBYQAFIXAxARHQROFVQYFwgHHAis7Ai1+hAeQQ==",
  "JBwWVA4NChoBBBhCHBut90cDFAEYGB1IShEcFwSr61QLHxMRTwEZqv4UGxwZFlIeShgGDhgFq/FG",
  "IRS2yAUXTxUDCgAGTxAIHAgHGFMEGxMOD1UAHaX3TxcHFxMYTx6s0gIaEgkOQQ==",
  "PgIcHgBOHxUFDLb7q/VJAw60+LbsARsLHRRTBBMPDAECAFIGAxNJLQ4VAxoSTxwFHRAHVBEBTwAaABwLARUcQA==",
  "LRwHFRMPTwAHRRkOGhETTgMfQRYaABEOA1lTHxWt3AYRBhpCARsMTgMRQQAeq+tEHQwBFRsHq/NIFrfgAAUIAw5e",
  "r+8EHQQaAR0NRQUbBB0bFB4DFRIZFlIHEBQAVIPu/FQKFxMVAFM=",
  "OBoJAwgEDgcSRQELq+tJGUcEBB4HBhdISh4Ht9IcClQCAAEWTxYFD0czCBYVBhdEAxEWFQ0AClo=",
  "PgIcHgROHBsEClIYTxkIq9sUGB5XCxwNDxhTGgAMBhEaBFIBBxMbDwwEBAECQQ==",
  "Lg8asfpOHxsDChwDqvAMq/xQDRYZBgEQHRpTHUEeAAccBAULqvAMq/xQDxJXHR0eHbbAHk8=",
  "JwAJDQoPQ1QDEbHRHbbsTgACAAANQ1IeBQYHFQsLTwNIMQUNBh9JHQICAgZXARNEDrDxAaTSCh5G",
  "OhoQDhQETwMBBwADDBgMThQEEwYZQ1IPHrbABgROHwYSABZCDBoeBwu05FMCDBsXEAy29gSr9Fo=",
  "PhpTGggLHBUFCgULGxdFTg0RClMEFQsGARpTBg4MBgcSRQINHAat9xcJTVMQCwtErvIEHQIUFgcSRQAHCAcFDxUeCBZZ",
  "PgKwxwtOHLHqEBEKTxoIHAofDxoUFRwdSgYHFQsLTwcBoetCDB0bDx1QDgADHQgBAAYJDU8=",
  "IRS2yAUPTxodERNCAhNJFAkRAgkSARsBRlUSVDUXTxAKBAEYTx1JBQa13Rez6lIeShsaFwlA",
  "KLH2EKTUTxAEBFIRBhcLBwJQFgoFAAgRBxwSseMXT5bo9lISHR0KCxRQCxYEG1IQCx5TBwADAFQfBLfeAQtJBAYbQRASA1w=",
  "LQcSGggLTxoJRRULGxMbFAJQFRxXHwABEBAdAE1OBACr1gAbTxYIBAIDG1Oy9AUNCwEGWg==",
  "PgIcHgBOGxELDRwLBBNJBQgDFRgYGBMKAxRTBxUPBRFIFhum9lIKARURG1MVDgAAEBwWHkEeqvYRCxwDQQ==",
  "IBAAAASr9FQaHxen1RAADxUKBB5XC7feHRy37QobQQ==",
  "Lg8aBwgLBQcSHFIWHRcHBwkXQQcYTxYLHbbAEEEADlQ8ErHRBVIaFAYTFB0SBFIABVUEseMPHBoRBhpCHxMaBA5e",
  "MFUYFaTSC7DtRQEHHBit60cTDgEWFVIIDwUaEQtOHRsSEB8LCgETTgMFEgmz9lINBAYHBhQDChocEFw=",
  "JwAJDQoPTxAHARMIClIaBRUKGBcSqvBIShRTIBhOGLHqBLf5ARsMTg0VQQEYFbfmBbDPDaTsCrHzSw==",
  "PhAUG01ODBtIAQgLqulJGR605gQeDAgdr/cWsfpCTxoBDgZCLBtJBBK13VMZBhdEBRERHQQcFRFG",
  "PgIcHgBOBBsGBhcMGwAIDQ0RQQMYCxEeCwZTExMXTxYRoPADTxsEHggeFBmz6hEFRA==",
  "LRwHFRMPTwAHRSYVABgIThQFERYFAh0HSgJTFw4KFR0NCxwbAlKs9RAZBBAeClw=",
  "PbDxFaT1AR0NRR0WGB0bFB614xay9FIXBRcaEUEKHQ4fDFIGAFIHARAJAhtXAgceExYJGhgNB1QFCrfeAxseAaLrAhpZ",
  "PgIcHgROAAQdFggJBlIZDwsTosAATwEQCx+38UEdBrDxRQYVDgANHR0VTVMWTwEBGBYWVAMPHRASDBcITwUbD6LMDRoAClw=",
  "IRS2yAUPTwcNFhgDTwYGTgkfFhJXAAILHRwWsfqq6FhIDgah3ACt60cfERwABhMACwYJWg==",
  "Lg8asPgFGh6s/FIhBlITD0ckFrDEBVITAbDxFQVOGFQ8Eh0Iq/dJGaLyAAAZq/dEHgKwxxMNFRut/rblQQ==",
  "OhQeHaX3GxUCSVKn0xdJBQa13RcOTwILGQG37RFOFRULHwsMDlIaB6PpQRwTTxYBCQwJHghCTxYRRQgDDAit66P3Tw==",
  "PgIcHgROHR0OAwtCHAYIBKP1QQAeq+tECRoBFRtODRUaAQgLChhJHQgTGwoEGxdK",
  "LQcSGggLTxoJRRULGxMbFAJQFRxXARMOBhADBxsXTwAaABwLARVJCgsRQScAABgBAFUGAwCr0xoHoOkBBlw=",
  "Lg8asfpOCxsMBLfgCrfyTgwfDRYdAQtEARofGxNOCxtIFgUNBRcDTgoFGwoUFRwBAFUDFQ0LGw1G",
  "PgIcHgBODB0NFwIOBgUGq/y05lMTAFIQGAAXGhgNB1QOFxMFAhcHGqTDFlMdCgEQShIcEA8PTxkBFgYQFRNH",
  "PbDxFaT1AR0NRQcGAAUGCgkZpPESqulEGRoRHQRCT7HUAFISAAYbDwEZEglXC7bhr8kKsOZOCxtIBhcOGlw=",
  "IRS2yAUXTwMRBwAYAhsIq+UJQRIcAAAASgEcVDUZAB4NRR8DqvAMTgMKCBay7R1EGQ8HAQoHQQ==",
  "r+8EHQAaTwQHEQAYChAcBAJQNQQYBRcOShgGDhgFBlhIofUVBhETTgMRDRYdTg==",
  "PhpTFhir7VQOBBwWDgEdFwQKDwpXCRsKAwYJWEEUDget5wen0wus7AK1+lMZDlILDgUcFxsXAREDRA==",
];
export const useVaultStore = create((set, get) => ({
  pass: localStorage.getItem("vault_pass") || "",

  setPass: (newPass) => {
    localStorage.setItem("vault_pass", newPass);
    set({ pass: newPass });
  },

  getRandomSentence: () => {
    const { pass } = get();
    if (!pass || ENCRYPTED_DATA.length === 0) return "No password or data";

    try {
      const randomEnc =
        ENCRYPTED_DATA[Math.floor(Math.random() * ENCRYPTED_DATA.length)];

      const binary = atob(randomEnc);
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);

      const keyBytes = new TextEncoder().encode(pass);
      const result = bytes.map((b, i) => b ^ keyBytes[i % keyBytes.length]);

      return new TextDecoder().decode(result);
    } catch (e) {
      return "❌ Wrong password!" + e;
    }
  },
}));
