import { create } from "zustand";

const ENCRYPTED_DATA = [
  "LQcSHkEaDh9ERRgDBBAQThS05AAeChYeA1UEseMPqu8GDBdCBAcZARARDRpXDRsIDwEKVA8PTyAfpsEITxkGAAQVEwdW",
  "PgKwxwtOAhEcFx0MAB9JBaLyAB4eClxELQcSBxtOBhANBB4MBhdFThMfQRwZTwIWEAwABAgLHA4JRA==",
  "IRS2yAUXTxIJoPARFQseF0cUpMkABrb9AVUHG0EeAFQYFx0RGwdJSQ0RGwkYGBNEAxsHERMeHREcBBEIDlVH",
  "PgIcHgROAAQdFggJBlIZDwsTosAATxARDgAZsOROHxUGBhcQFVIOAQMeGFMEGgIBGBccHAAaCgYJRA==",
  "IhAdEBMHF1QYBAYQFQtJFEcXosAFFlINSgK29gCr9BoBAFISABkIFAa141M0BlIPCRwGHwBOGFQPpsEQq+tH",
  "OhQeHaX3GxUCSVIRAB4GThQRDBxXHBug81UdHQROFRUPFxNOTxNJHaP1EhoSCwgNSgYSGQhOHB2s/FIMBhdJGR4AExwADhYervBd",
  "MBQUBgAETwAHRRgHHAgKFAJQExINQVIwExhTBgAUChlIH1IPBhyt60tQCxIcDQuh8VUZFQWr7VQKBAAGFR1JBRARpOgZq/dECQwHBhgAq+1J",
  "PgIcHgBOCB0cBAADTwat9xQbDxqy7RNEEBRTIA4Mq/FIFQAYCghJDQa14xZXV1IDBREJHQ9OGFQYFxMBFlw=",
  "IBAXEQ9ODBwfHAZCCwgACwsZQTAeq+tEBRFTDg4dGxUGDBNCAxcOCwkUpfZXABUKAwYYFU8=",
  "KLbAGEEeDhgLpsEVTwYGThMJDRgYTwGh6BQRG6T1q/NICgIXHAgKFAYapfYUDlIwHRoZEUENBhWt5x1D",
  "LQcSHkEJqvYHoOkMAFxJIA4VAhtXAAENDxEfEUEZBhFERRkWAFIdG0cCG7fyCwgNRA==",
  "JBQEERVOPBgJFhpCBBsMCh61+lMZBhdEHRwWEBsHDrHqSVIFCwgAC0caBAADTwEQGAAdFUEpQQ==",
  "PgIcHgROHxUEBhdCHLbsTgMKCLbsTwEeExcADgROAR2t2VKn9AUADxO14xwArMEASw==",
  "LQcSHkEaDh9ERbfeChAQThQEEwYZFlIGr/cSEwCr7Q1IClIOBgYGq/y05l0=",
  "JBwWVBEBGwYSABAXBRcaFEcEBAEWHxsNRFUjGxUcFREKEBgHHAhJGQ60+BASBVIUGA8WBxULHQFJ",
  "PbDxFaT1AR0NRQgDHR0LB6LyBLbsT0NUWlUDAQ8FG7fbElIGAFIKBgYCGAkaFlw=",
  "PgIcHgROGB0KFxMWAFIDCxQEQQcWBFIXBRYJDRIaClhIoM4HTx8Gq9seAFMNTxwNDxIcVBscABYBofVCC7fVCwpe",
  "PRy37QILBVQPBBsMGlNJq/0HCBIDTxgBGQ8QDgROAR0NRR0FqvAcDQ+141MAFgEQCwcQDgAEq/ELClM=",
  "Lg8asfpODQYSCBsRFVIDDwxQDBobBh0KShEcGAAcrMcfRVoSHQgMCkcfERwTDgYPBQISGggLAl1G",
  "LREKFhhOCB0cBAAbTx8GCaLyGFMarMETA7H0WEE6GBsCBFISAAUACwMKCBKy7RMGE09TUyUPGBUCRQULq+sKCw1RRg==",
  "PgIcHgROC7HqChwLClIdAUcEBAEWFVIUGBAQDRsXBRoNRRwDHQit9wMKCBJXDBoNGAABEwgNFRoNSw==",
  "MBQUBgAETwAHRQYDBF5JBAYbAwpXABZEHhAUG0EUDhgNoM4DqvAQTgsfEgpXCBMICx4HDQoHQQ==",
  "IRS2yAUPTxkBCwcWDlKt6RAZAgkSqvZEHhpTHgQKChpIDgANBFINDwsVC1MYC1IGExYaFUEPAhUcCgAHAlw=",
  "JBwWVAwXAx0bH1IRBrbwQkcADlMHHR0XHgBTHw4DHxsGEBgHHAhJAAZQpM8OGB1F",
  "MAewxwNOGxUDofdCAhsHqv5cQbbLChAdSgIADhgdDA1ICAun9B4MAg5cQbbLClIQBVUdFQsaHQEMCxsHBQETC0cDDh8YT7f/HRwSAABA",
  "PgIcHgBOCB0cBAADTwceD6LMAF9Xqs4BSgccFggdFVQHAgANAhwMThcfEgez9gIdRFU5FUEaCrHUSw==",
  "PhAUG0EKqs4fDLb7BAdJAA4VQREOqvALSgJTAAAMGhgJEQcQFRdFTgUfQREOqvBEEBRTEA4MHQ1J",
  "IBAAAASr9FQHRRgHCxwGTqP3FhoUFRcKAxBTGwVODQ0LDBNCAxcZHR0JDFMZBrfYSgIQDg4cDh5G",
  "PQwfARsbBVQGBBYFDgAaGgIbT1MgFh0GGBS2zkEdABYBAF5Cqs4MThQEEwkSHwcODwYJVBYBC7DxRQhCHbbsBUk=",
  "PgIcHgROBBsbERkNGBMHBwJQCxYEG1IAEBy270EBHAAaAFIIDhlJDBUKGAcADlw=",
  "JBwWVBEcFREbERMVDhhHTjUfAhhQAVUWBRkfVA8HClQSCxNCHLfrARARQVQSAhcWEwEGBgBJQQ==",
  "LQcSHkEaDh9ERbfeChAQThQEEwYZFlIIr+4dHaTsFlQHAVI2GB0DCw1QBB0SHRUNA1Q=",
  "IBAAAASr9FQMHxun9FIeThMCGBEeClJDKBAAAAgPSFpIKxsHTwIaGw1QFRYQAFw=",
  "PgIcHgBOAxEfBFIQq+sCD0cEDlMDCgAFEFUeFRIUFhoJRRYNTwIAHQYeCBJXBxsQqcYEWg==",
  "OhoQDhQETwANC1IRGgEdDw4eT11ZTwYWEAweFaTsDQ1IDxcRFRETC0cUDlMdGgYWC1Q=",
  "LQcSHkEaDh9ERbfeChAQTh0RGxcFALf/CRwfHUEtBlQGBAUHG1IZCxUbFAAequkHA1s=",
  "PgIcHgBOCB0cBAADTwWs7Aa1+h0eClIJGAAYGqX3qvYJRQhCFRMKBhAJFQZZ",
  "JRkWHkEeHRUGDBdMTz0FCw1QDxIUFQsKAxRdVCwPHA5IFh0OAFINAUcUDgMFDhELHRQdHQBP",
  "Lg8aBwgPBVQ8ErHRBVIPCwIUAxIUBFIGGA8eHUEEDh9ICAcYFhkIThQWBAFZ",
  "IBAAAASr9FQJFxEKBgYMBRMVDFMTqsgTA7HqHxRATzYdAQcITwYGTg4dERYFBgcJSw==",
  "JBwWVAOt3B5IFhum9lILq+W0+BcCQVImr/e38QVOGxtIFR0BFbbsGgIbQR0YGBcOShgWGA4KBh1G",
  "PgIcHgROHxUEBhdCGxOs6gQKpfZXARNEDQcKEggLTxgNFRsHBVIHB6LMQREWAxcQBBwQEU8=",
  "PbDxsOQNFVQHExcQCwAAGAJQCFMEHxMISgEWVAoPAxsaDBdCARNJCRUJBxoSTg==",
  "PgIcHgBOGxELDRwLBBNJBAIDFVMTFRuh8VUQDhgdGwcSBFIMBrfVTjMHDhkSTwERBxwWGggLQQ==",
  "MBQUBgAETwAHRQhCGxMCquJQERIEBbbhRlW2yAQMFlQbEQAXAQtJHqPpCrb1FlIeSg8SDgUcALHzBhtM",
  "IRoAAAoPTwNIAbfgALftTg5QBRxXHwAeBREGVUGr9QMBBAZCDAgMBQZe",
  "JBwYAEEABhFIAgADTwYMCQhQExoRCQdEHhQYVAsPBFQ8HFxCPBcbBwhe",
  "PgIcHgROGhcAClIVqvAIq/weCBZXHAYFr/ccVBIHq+1IClJTWldJDAYCBQkeChhECQ8GseMLQQ==",
  "JhAUEQ8KDlQFpsEVBl5Jq9sVQRgDAFKg7QIaFxsXT0VdRR8LAQcdTgMKCBYZARsBRlUHEQ9OAR0NRRsGFRsMTgMfQQMeChmh6BRd",
  "IBAAAASr9FQHRRkQABlJAQNQRgADHRcCE1JdVC8HClQfHBEKABas1EcKQR0eChhF",
  "PgIcHgBOCB0cBAADTwYGThWz0rbLC7fYARRfVABOOw1IDxcRGxes9UcTCRwbCgAKExhTPAAcHQ0FRSINGwYMHAIdTw==",
  "LQcSHkEaDh9ERbfeChAQThS05AAeChYeA1UJFQIUq+0EDFIRGwcCD6P3QRcYTwAdHhgGWEEPTxoBAFIVTwAcHB5e",
  "PbDxFaT1AR0NRR0GDR4GBQgHALb1Crf/ShscAxhOHxsSDB0PTwUdDw0VDB0eDAgBBBwSVQ==",
  "PgIcHgROJxUFCBcQQh0HSR5QAwENAhug71UZFQpOGA0bEQAYDrfrF0cKQRgWHRMGAxsGWg==",
  "Lg8asfpOCAYJFghCGxMCQke13RZXARMTDwFTGQQaHRsGCh9CDBoKC0cEALbzDAgdrvJd",
  "PgIcHgROHxUEBhdCAhMDquJQBQkequlEHbDxFRIAFlQGBAKm9hZJAQMCGwYDAAUdRA==",
  "JBwWVBEPGwYSRRwDTwIbAQAZT1MnABEeHx9THgROHBEaBhcPT1oATggAFAANBBMJA1xd",
  "IRS2yAUXTwcEDBYHTwYGThcfBQG03LfYSgJTGggLFRoJCxdMTz4MquBR",
  "PgIcHgRODh8HFxYbTwGt60cUGxqy9FIQHRQBEBIUClQGDLfeTxYADwoVDwdZ",
  "LQcSHkEJqvYHoOkMBhcDT0c+CBYUB1IPBQYeGw8PGhcBRQYHqs5JDQi1+lMNTwYBDRpTGQAEq/FG",
  "PgIcHgBOCB0cBAADTwIbARQZpPEWQ1Kh1hARDaT1Tx4ND1IGFRsaBwYaQR0eClILDh629gAKDrHqSw==",
  "IBAAAASr9FQDF7HRAxcETgACGBUCQVIvBQccGgBOHxUbEBgHTxsNCwYcDxoSQQ==",
  "PgIcHgROHBsEClIVqvAIq/weCBZXHAIWCwIaseMBQ1St2RdCBBMeD0cdCFMAFgEQExK29gBOFVQfFxOn0xcHBwZe",
  "OhoQDhQETwANC1IQFgYEQEc6BAADCrf/SgYWBgILAlQcABUNTwIGBQgaFF0=",
  "LQcSHkEaDh9ERRgDBBAQq/xQAhsUBhOh6FUGAwgLqu+s4lIBDrfrF0cDFRITBh0KRA==",
  "PgIcHgROHxsMBhum6hUHB6PpAhoWTwGg71UHFQpOHwYNBgsYFhgHC0tQpM8STx8Lr8kdFUEZCFQGDBEKTwEdHAgZpfRXCR0WHhADHQAAFlo=",
  "MBsSBxtOBQGt2VINTxgMCgIeQRey1QUNruwYVBYHq+0LABhCARus0kcdCB0CG7b9SgEWGRRATzYaBAUNTg==",
  "JBwWVBIUGh8JD1IVFh+q3RAVCl1XPAgRARQZVAoBHAADDFJKHxceAA4VQQQHDhah6BRTEA5Oqu8aChYJDltH",
  "PgIcHgROHxUEBhdCGx1JCh0ZpOhXCwgNDwYasPgNBgFICBOn7QsKBkcHCAEDGh0eqcYEWg==",
  "LQcSHkEUTw4JCBkMBrbwGh4dCFMYDAgFBxxdVDsBDRULH15CDB1JHQ60+FMEGxMKAxBS",
  "PgIcHgBOCB0cBAADTxgMHRNQBQYaARNISrDPEUEEq/FIEQAYFh8IHR1e",
  "IBAAAASr9FQMHxsRBhMDTgkZBB8SCBMIBBwWVBQaDhgNCwYNGBMHF0k=",
  "LQcSHkEaDh9ERRgDBBAQq/xQERoEDrfmShkaBxVOAh2t5x0RAQtJCghQDAYNFhkNRA==",
  "PgIcHgROHxUECFIPGgYAAABQCxYEG1IQCx5TAKTsGgccAF5Cqs4MThcfFQENChARALHqVBILHQMNERkLQQ==",
  "PbDxFaT1AR0NRQEWDrfrC6LrQQAeq+tEAxsABAgcDhcCofdCCx4IThQRDBYQAFIXAxARHQRA",
  "OhQeHaX3GxUCX1InHRsKTiQcAAMDABxEHhC2yEEFBhEMHLf5TxwAC0cFDBoWqvBELFgXARNA",
  "PgIcHgBOCB0cBAADTx8ITgMKCLbsTwUdALH2AAoBGBtIAR0AHQtJBhIdDgFZTyUdARoBDhgdGxUCRQYNTg==",
  "LQcSHkEaDh9ERbfeChAQThcfFhoSGwAeD1UEGwqt3LHqRTELChAAC0cKABANq+uh6BpTAwgMHRsfBLblQQ==",
  "PgIcHgROHR0OAwtCHLbsTgMKCLbsTx0XHgcWVAsPBFQYBAIQFhETBQZQCRIVDhwBGBpd",
  "JBwWVAOt3B5IFhum9lIKBxQKGFMaBrb9Dg8KVAWr1QMBoesJDh8AQEckDlMDCrfYShgGDhgFDlo=",
  "PgIcHgROC7HqChwLClIdGQgCG7fyTxoNGQEcBgiq9lpIKxsHTwIbFAIDFRIADhhEGhwAFaXpQQ==",
  "IBAAAASr9FQHRRgHCxwGThcfFge03AAeDxsaEUEBC1QYAAAEChkKBA5e",
  "PgIcHgBOCB0cBAADTxEBDQJQBQkequlEHwa29hgdFRGs4lIBALfyTgkfFhYQAFxEMBQAHw4NFVQCofdM",
  "LQcSHkEaDh9ERbfeChAQThQEEwYZFlIXHhS29hhOHB2s/FISHQgMCqLyFLbLChwNDxhTIBYBBRECRRYXHAgQQA==",
  "PgIcHgROGxEFFR1CBRcaGkcDFRIVBh4KD1UZFQpOCQEGARMPChwdF0cHCBay0x0TCRRd",
  "PbDxFaT1AR0NRQINBB0HD6LyBLbsTwETBR8WVA0LAR0bEQUNQVI+FwkZCklXXkhUShEfFUEDGg4RDhtM",
  "PgIcHgRODh8HFxYbTxAIHAgHBFMEq/dEDg8asfpOAR0NRRYNTwgNDxUTCBJZ",
  "LQcSHkEaDh9ERbfeChAQTgwRpM8TFlIAr88EHaX3BFQFDBOn7VITAAYTGxYZBhdK",
  "PgIcHgBOCB0cBAADTx6s9QkZQRwTTyYTBR8WEw5OGxUEABwWGlJBDwsSDlMDAFIUBQFfVA8HCh0bER0WARdAQA==",
  "IBAAAASr9FQMHxun9FIeBxUEFBwNCh9EHbDxFRIAChMHRQURFRcKBqLrFhoWGxNK",
  "OhoQDhQETwANC1IFHR0GGAJeT11XARMTDwFTGQQMAxFIHxMBFQsHDw205FMEBrb9ShcGHgCq6Fo=",
  "PgIcHgROHBsEClIAFrfrAUcEABhXCx0GGBBfVKTSClQDCgZCHwATCxQEALb1Tx8NCwAQDgSq6Fo=",
  "LQcSHkEUTxsMEhMFq/dJAhARQRpXHwABCQwJHqXrTxcADAAXHRUIQA==",
  "PgIcHgBOCB0cBAADTwYGTgkRCx8SHwEeE1UDBhsXBRULDBcOT5Dp/UceCBQTFlIKAxBTAxgKDlQ8Eh0LDBpJHQIbExYDrMETRA==",
  "IBAAAASr9FQHRRYYBhcaB6PppfRXAhsKHwFTFg0HqsgND1IGAFILFwQZAFMVrMEXHgIWGUEJBgAJFwtM",
  "LQcSHkEaDh9ERbfeChAQThQEEwYZFlKh8QUaERYPqvYRRR1COwUGBwQYQR4WHQgBBBwSFwlA",
  "PgIcHgROBBsbERkNGBMHBwJQDxIHHQgBBxwWGg8LTwAHRRYYBrfyTgQKGAADDlIUBRAJHgBA",
  "JBwWVA0HDA5IAh0GFRsHQkccCBANTwAFDhq276XpTw5IDhOn0xYMCQhQAgkOHAYBDRpTEKTUGB2s/BkXQQ==",
  "PgIcHgBOCB0cBAADTxETCwwRpPEWTxwFSgEWGkEcBhIORR0GTwAIAAZR",
  "LQcSHkEKDhgND1xCqugeBwYEQQMYGwAeDxcGHgROOwMHDxcFAFILHB0dCBYZBhNF",
];

export const useVaultStore = create((set, get) => ({
  pass: localStorage.getItem("vault_pass") || "",

  setPass: (newPass) => {
    localStorage.setItem("vault_pass", newPass);
    set({ pass: newPass });
  },

  getRandomSentence: () => {
    const { pass } = get();
    if (!pass || ENCRYPTED_DATA.length === 0) return "No password or data";

    try {
      const randomEnc =
        ENCRYPTED_DATA[Math.floor(Math.random() * ENCRYPTED_DATA.length)];

      const binary = atob(randomEnc);
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);

      const keyBytes = new TextEncoder().encode(pass);
      const result = bytes.map((b, i) => b ^ keyBytes[i % keyBytes.length]);

      return new TextDecoder().decode(result);
    } catch (e) {
      return "❌ Wrong password!" + e;
    }
  },
}));
